### ISSUE TITLE
Extend release draft with uninstall and upgrade instructions

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/ReleaseDaemon#15]
Currently in 1.0.5 the release draft is populated with install section. We need to extend this to contain **uninstall** section, and for x.x.x.1+ releases with **upgrade** section as well. Proposed upgrade section text:

If previous version of patch is installed, please uninstall it first. The uninstall instructions available here:

* link to x.x.x.0 release
* ...

**Comment by AlenPelin** [comment]
@olegburov @RomanChernyk your opinion on that?

**Comment by olegburov** [comment]
It would be handy if we have both instructions for **install** and **uninstall**. Maybe the **upgrade** too, but in most cases we just overwriting the same files.

**Comment by RomanChernyk** [comment]
Agree for uninstall. Not sure for the upgrade. Do we have any specific examples when the upgrade process is unclear?

**Comment by AlenPelin** [comment]
Not really, but it is better to have at least general phrase "If previous version of patch is installed, please uninstall it first" for those customers who demand crystal clear instructions.

**Comment by AlenPelin** [comment]
Agreed to have uninstall only and update todo section.

**Comment by AlenPelin** [comment]
We agreed that first we need to review the suggested text here in comments.

**Comment by SC-AFI** [comment]
The proposed text of the instructions sections is below. Please review it. @olegburov @RomanChernyk @AlenPelin 
The first step of the Installation Instructions will be added if the 4th digit of patch version (patch revision, own patch version) is more than 0.
#######################################
##### Installation instructions 
1. If one of the previous versions of the patch is installed, please uninstall it first. 
2. Examine the 'Contents' section and back up the files of your solution which will be replaced by applying this patch. 
3. Download the [Sitecore.Support.123456-8.1.1.1.zip](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases/download/8.1.1.1/Sitecore.Support.123456-8.1.1.1.zip) file. 
4. Extract the archive to the `Website` folder of **all Sitecore instances** in the solution, overwrite the existing files if any conflicts occur. 
 
##### Uninstallation instructions 
1. Remove the files which are listed in the `Contents` section. 
2. Restore the original versions of the files which were overwritten by this patch. 

#######################################

**Comment by AlenPelin** [comment]
I propose to change format a little bit:

### Sitecore.Support.147434-8.1.3.0.zip

#### Contents
* bin/Sitecore.Support.147434.dll  <sub>[md5:8FD8EBE33E85240BCC126C43ED209662]</sub>
* sitecore/shell/Override/OneColumnPreview.xml  <sub>[md5:6C99D5CD7153895853DE5B31A545C05A]</sub>

#### Install Steps

For **all Sitecore instances** in the solution:

1. Uninstall previous version of the patch (if installed).
2. **Make a back up** of the files mentioned in **Contents** section
3. Download and extract the [Sitecore.Support.147434-8.1.3.0.zip](https://github.com/sitecoresupport/Sitecore.Support.147434/releases/download/8.1.3.0/Sitecore.Support.147434-8.1.3.0.zip) archive to the `Website` folder, overwrite existing files if any conflicts occur.

#### Uninstall Steps

1. Remove the files listed in the **Contents** section.
2. Restore the original files from the back up made during installation.

### Important Notes

**Comment by AlenPelin** [comment]
Or 

...
#### Installation
...
#### Uninstallation 
...

**Comment by AlenPelin** [comment]
@SC-AFI @RomanChernyk @olegburov what do you think?

**Comment by RomanChernyk** [comment]
@AlenPelin I like your proposal and the last mentioned headers. However, would move the contents section to the bottom.

**Comment by AlenPelin** [comment]
@RomanChernyk I suggested to move the contents section up to make customers notice it. It became important as we demand making back up of default files among them.

**Comment by AlenPelin** [comment]
**Changes:**
* Updated headers
* Slightly modified install steps 1 and 2

...

### Sitecore.Support.147434-8.1.3.0.zip

#### Contents
* bin/Sitecore.Support.147434.dll  <sub>[md5:8FD8EBE33E85240BCC126C43ED209662]</sub>
* sitecore/shell/Override/OneColumnPreview.xml  <sub>[md5:6C99D5CD7153895853DE5B31A545C05A]</sub>

#### Installation

For **all Sitecore instances** in the solution:

1. Uninstall previous version of the patch (if installed). **[show only if 4th digit > 0]**
2. **Make a back up** of the files mentioned in **Contents** section that already exist in Website folder
3. Download and extract the [Sitecore.Support.147434-8.1.3.0.zip](https://github.com/sitecoresupport/Sitecore.Support.147434/releases/download/8.1.3.0/Sitecore.Support.147434-8.1.3.0.zip) archive to the `Website` folder, overwrite existing files if any conflicts occur.

#### Uninstallation

1. Remove the files listed in the **Contents** section.
2. Restore the original files from the back up made during installation.

### Important Notes

...

**Comment by RomanChernyk** [comment]
Ok. agree
