### ISSUE TITLE
Allow creating releases without compatibility details

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/ReleaseDaemon#20]
In current implementation (1.0.5.1) when something goes wrong and compatibility section cannot be created, the release creation is abandoned and only error details are shown. We need to make release assembly go on and provide error details in the compatibility section letting developer fill it manually.

**Comment by AlenPelin** [comment]
Due to GitHub limitation that prevents retrieving emails of users, we agreed to make GitHub send emails itself by making ReleaseDaemon post comments to the https://github.com/sitecoresupport/notifications/issues/1 issue via SitecoreBot with following text:

@username, the release draft was created for [SitecoreSupport/Sitecore.Support.Example@7.2.6.5](https://github.com/SitecoreSupport/Sitecore.Support.Example/releases/tag/untagged-2c721c0562095d697c2c)

```markdown
@username, the release draft was created for 
[SitecoreSupport/Sitecore.Support.Example@7.2.6.5]
(https://github.com/SitecoreSupport/Sitecore.Support.Example/releases/tag/untagged-2c721c0562095d697c2c)
```

**Comment by AlenPelin** [comment]
We agreed that first we need to review the suggested text here in comments.

**Comment by SC-AFI** [comment]
Please review the content of the Compatibility section. This content will be shown in case the section cannot be generated automatically. @AlenPelin @olegburov @RomanChernyk 

#### Compatibility
> IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT!
> **Warning!*** Failed to create the 'Compatibility' section.* 

> @SC-AFI *please fill the section in manually. It is highly recommended using the following template:*

The release was built for and tested with the following Sitecore products in bare condition(no hotfixes, patches or other customizations, unless explicitly specified):
* Sitecore Experience Platform X.Y rev. yymmdd (Update-Z)

> IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT!

**Comment by RomanChernyk** [comment]
Looks nice.

**Comment by AlenPelin** [comment]
Small corrections here:

#### Compatibility

The release was built for and tested with the following Sitecore products in bare condition(no hotfixes, patches or other customizations, unless explicitly specified):

> IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT!
>
> **Warning!** Failed to create the **Compatibility** section, please report this behavior to [the team](https://github.com/SitecoreSupport/Readme/blob/master/TEAM.MD).
>
> @AlenPelin, you must fill the section in manually using the following template:
>
> * Sitecore Experience Platform X.Y rev. YYMMDD (Update-Z)
> * Sitecore Module Name X.Y rev. YYMMDD (Update-Z)
>
> IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT!
