### ISSUE TITLE
Add issue report and contribution section to release draft

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/ReleaseDaemon#22]
Currently in 1.0.5.1 we don't have any information in the release draft and repo readme file. We need to add this information, but first need to figure out the exact form of it and align it with https://github.com/SitecoreSupport/Readme/issues/12

##### Important Notes
* The patch should be installed only if your solution is affected by the described issue.
* Any related issues and other feedback should be reported via [support portal](https://support.sitecore.net), check [KB 654910](https://kb.sitecore.net/articles/654910) for details.
* Check <a href="https://kb.sitecore.net/articles/077333">KB077333 article</a> to find more information about Sitecore Patches.

**Comment by RomanChernyk** [comment]
Looks nice.

**Comment by RomanChernyk** [comment]
@AlenPelin can we do this in the nearest time? Hope, this should be relatively easy to implement.
