### ISSUE TITLE
Add shields analytics to releases

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/ReleaseDaemon#23]
Add shields analytics to releases
http://shields.io/

**Comment by olegburov** [comment]
Releases or README in the `master` branch?

**Comment by AlenPelin** [comment]
Readme - All Releases
Releases - By Release

**Comment by AlenPelin** [comment]
Reopened:
* "All Releases" shield is not added to master branch.
* Move release shields to the bottom of release draft

**Comment by SC-AFI** [comment]
The following issue should be realized in the 'PatcCreator':
"All Releases" shield is not added to master branch.

New issue for PatchCreator has been created:
https://github.com/SitecoreSupport/PatchCreator/issues/24

**Comment by olegburov** [comment]
In a release's deception, a shield for specific version looks a bit confused, because we don't use the `v` prefix when creating tags. 

For example:
https://github.com/SitecoreSupport/Sitecore.Support.147688/releases/tag/8.2.0.0

To me, it says *Downloads 18200 times* instead of *Downloads 1 time of version 8.2.0.0*.

**Comment by AlenPelin** [comment]
@olegburov I agree, it does not look very nice. But I am not sure that it worth changing our tag formatting style just because of this. @RomanChernyk @SC-AFI ?

**Comment by olegburov** [comment]
I don't think we should change our tag formatting, and I also don't see how we can work it around based on what https://img.shields.io/ supports.

Maybe we just need to drop the shield badge from the releases and keep it only within `README.MD` in `master` branch. For example: https://github.com/SitecoreSupport/Sitecore.Support.449298/

**Comment by AlenPelin** [comment]
@olegburov well, we do need to know how many times each patch version is downloaded. So this badge has very pragmatic reason to be here. It does not look really well, but in my opinion it is not that important.

**Comment by SC-AFI** [comment]
I agree that "1 8.2.0.0" looks a bit confusing, but it shows how popular each version of the patch is. I think we should preserve the badge and 'move release shields to the bottom of release draft' as it was suggested by Alen.

**Comment by RomanChernyk** [comment]
Agree, that it is not worth our attention that much :) When we need to understand the numbers, we will be able to do this.
Let's leave the things as is, just move the badge to the bottom of the release.
