### ISSUE TITLE
Add support for external NuGet packages

### ISSUE THREAD

**Issue by RomanChernyk** [SitecoreSupport/ReleaseDaemon#27]
Currently ReleaseDaemon fails with the attached null reference exception when processing the external NuGet packages referenced by the project.

[GitHub_Release_Deamon_Run_30507.txt](https://github.com/SitecoreSupport/ReleaseDaemon/files/638813/GitHub_Release_Deamon_Run_30507.txt)

The reason is that the daemon expects the specific xml namespace to be used in the package metadata.
Namely http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd

While the namespaces is different in the external NuGet packages not generated by SIM.

**Comment by AlenPelin** [comment]
ReleaseDaemon supports only SIM-generated projects. The v8.1.3 branch of repository https://github.com/SitecoreSupport/Sitecore.Support.96688 was created manually.

**Comment by RomanChernyk** [comment]
Don't you think there might be a need to reference external NuGet packages sometimes?

**Comment by AlenPelin** [comment]
@RomanChernyk external NuGet packages are supported. Can you give me an example repo that uses 3rd party nugets and fails to build?

**Comment by RomanChernyk** [comment]
Here it is:
https://github.com/SitecoreSupport/Sitecore.Support.ExternalNugetTest/releases
http://build.pssbuild1dk1.dk.sitecore.net/viewType.html?buildTypeId=ReleaseDaemon_Run

And here is a build log:
[GitHub_Release_Deamon_Run_32758.txt](https://github.com/SitecoreSupport/ReleaseDaemon/files/639041/GitHub_Release_Deamon_Run_32758.txt)

**Comment by RomanChernyk** [comment]
Moreover, this exception blocks processing of all other repositories, so I needed to delete the tag.

If you want to repro just create a tag once again.
