### ISSUE TITLE
Find all patches for given product

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/ReleaseDaemon#34]
There is a global problem of finding all patches for given product that we need to resolve. Initially we decided to fix it via #25 and #26 due to GitHub search not working in non-master branch.

According to our current setup, master branch is reserved only for metadata which prevents code search work. However we can change this to fix this issue, and also simplify implementation of #5 

Suggested approach is #35

**Comment by AlenPelin** [comment]
@RomanChernyk @olegburov what do you think?

**Comment by RomanChernyk** [comment]
ATM I don't see the problem with this taking into the account we have already implemented [#25](https://github.com/SitecoreSupport/ReleaseDaemon/issues/25) and going to implement [#26](https://github.com/SitecoreSupport/ReleaseDaemon/issues/26)
