### ISSUE TITLE
Merge all releases to master

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/ReleaseDaemon#35]
According to our current setup, master branch is reserved only for metadata which prevents code search work #34. However we can change this to fix this issue, and also simplify implementation of #5 

The approach is following:

* when `8.1.3.0` release draft got published by engineer
* `8.1.3.0` release text and artifacts are copied to `master` to `releases/8.1.3.0/` 
* ReleaseDaemon merges its `v8.1.3` branch to `master`
  * `src/` folder from `v8.1.3` branch is copied to `master`  as `releases/8.1.3.0/src/` 

So in result, we have master repository looks like this:

```
v8.1.3
- src/Sitecore.Support.123456/...
- readme.md

master
- releases/8.1.3.0/files/Sitecore.Support.123456-8.1.3.0.zip (release artifact)
- releases/8.1.3.0/src/Sitecore.Support.123456/...           (release source code)
- releases/8.1.3.0/index.md                                  (release text)
- readme.md                                                  (original metadata)
```

**Comment by AlenPelin** [comment]
@olegburov @RomanChernyk what do you think?

**Comment by RomanChernyk** [comment]
Hi guys! Maybe I am missing something, but I don't see any benefit of this ATM.
If the benefit is described in the "Find all patches for given product" item, then I think that searching for the issues with the particular tag in TFS is much more convenient and provides more flexibility through the TFS queries such as filtering already fixed bugs, bugs in the current sprint, etc. This allows working only with the particular and very specific subset of patches.

So, I don't see the point of changing the current approach.

**Comment by AlenPelin** [comment]
@RomanChernyk But we anyway need something like that for #5, so if we don't want to merge anything to master we would need another branch e.g. `releases` or wiki.

**Comment by RomanChernyk** [comment]
@AlenPelin Why we can't just go through all branches, collect necessary info and dump it? Not sure, I understand the need in the "aggregating" branch.

**Comment by AlenPelin** [comment]
@RomanChernyk that's exactly what I meant. But the question is where to dump it to? If to dump it to another branch, it would be extremely easy to backup everything - just clone the repo itself to some place and you would have everything. Otherwise to back it up you would need to clone the repo and find where releases were dumped to and copy from that directory.

**Comment by RomanChernyk** [comment]
Ok, in that case it might make sense, however, I would vote for introducing some branch other than master for "aggregating" purpose. Or clearly say that no development should be done in master.

This is to avoid any confusion for customer and engineers seeing all this stuff right away after opening the repo.

**Comment by AlenPelin** [comment]
@RomanChernyk okay, it makes sense. Decided not to merge everything to master.
