### ISSUE TITLE
Compatibility section must be more specific

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/ReleaseDaemon#39]
We need to update compatibility section text to outline that patch is not compatible with any other versions and hotfixes of the same version unless explicitly specified.

**Comment by AlenPelin** [comment]
@RomanChernyk @olegburov @alexeyromaniuha

**Comment by RomanChernyk** [comment]
Check here:
[https://github.com/SitecoreSupport/ReleaseDaemon/issues/44](https://github.com/SitecoreSupport/ReleaseDaemon/issues/44)
