### ISSUE TITLE
Make patch installation disclaimer more strict

### ISSUE THREAD

**Issue by RomanChernyk** [SitecoreSupport/ReleaseDaemon#43]
Replace the following line:
`The patch should be installed only if your solution is affected by the described issue.`

with the following one:
`The patch should be installed only if recommended by Sitecore Support.`

Approved by ARO.
@AlenPelin, please let me know if any comments

**Comment by AlenPelin** [comment]
No comments, please proceed to fix it.

**Comment by AlenPelin** [comment]
Not released yet (it will be closed automatically).
