### ISSUE TITLE
Update patch compatibility disclaimer

### ISSUE THREAD

**Issue by RomanChernyk** [SitecoreSupport/ReleaseDaemon#44]
Replace the following line:
>The release was built for and tested with:

with the following one:
>The release was built for and tested with the following Sitecore versions.
>No additional hotfixes or patches were installed unless specified otherwise.

Approved by ARO.
@AlenPelin please let me know if any comments.

**Comment by AlenPelin** [comment]
Maybe slightly different form?
> The release was built for and tested with the following Sitecore products in bare condition (no hotfixes, patches or other customizations unless explicitly specified):

**Comment by RomanChernyk** [comment]
Looks nice, agree.

**Comment by AlenPelin** [comment]
Not released yet.
