### ISSUE TITLE
Add a badge to show that an issue is fixed. 

### ISSUE THREAD

**Issue by olegburov** [SitecoreSupport/ReleaseDaemon#63]
@AlenPelin @RomanChernyk @SC-AFI There are patches for some issues that have been already fixed. We need to mark such patches with a badge. For example: https://img.shields.io/badge/fixed-8.2_update--1-blue.svg

I put the badge in the following patches. Check it out:

- https://github.com/SitecoreSupport/Sitecore.Support.405677
- https://github.com/SitecoreSupport/Sitecore.Support.391039

Badge's `label`, `version format`, `color` and `link` is open for discussions.

In my example I put the following values:

- `label` = fixed
- `version format` = {major}.{minor} {initial release/update-#}
- `color` = blue
- `link` = to Sitecore's release notes where issue is fixed.

**Comment by AlenPelin** [comment]
I was thinking of creating new fake release that explains the issue is fixed.

**Comment by RomanChernyk** [comment]
Actually, I added the following section to the readme some time ago:
https://github.com/SitecoreSupport/Readme#7-fixed-bugs

(BTW, do you think it can be moved out from the "Creating Pactch" section now?)

I don't think we can automate this, so engineers should do this manually.
This can be a badge, but would this be trivial for engineers and easy to explain how to create such generate badge?

**Comment by olegburov** [comment]
It's not so hard to create a badge. I can modify the section that @RomanChernyk mentioned above with details.

Using badge I see two benefits comparing to a plain text:

- It's more visible when navigate to the main page of a repo
- It comes with a link, which we can point to a release notes where a bug is fixed.

**Comment by AlenPelin** [comment]
@RomanChernyk yes, it can be moved out of creating patch section.

@olegburov when customer installs the fix - he or she may subscribe to changes in this repo. In this case customer gets a notification when:
* issue is created
* pull request is created
* release is published

So adding new "Fixed" -ish release will notify all customers. Badge in readme.md won't. But I don't see any harm in doing both things.

**Comment by olegburov** [comment]
I checked 10 random repos, and only in one I found a subscriber outside of Sitecore org who is watching for changes. Adding new "Fixed" -ish release will help, but we shouldn't count that it will notify all customers.

Let's use both approaches, where badge points to the "Fixed" -ish release, and the last refers to a specific Sitecore release notes where a bug is fixed.

**Comment by AlenPelin** [comment]
> Adding new "Fixed" -ish release will help, but we shouldn't count that it will notify all customers.

Unless we will request customers to subscribe. 

> Let's use both approaches, where badge points to the "Fixed" -ish release, and the last refers to a specific Sitecore release notes where a bug is fixed.

Sounds good.

**Comment by SC-AFI** [comment]
@AlenPelin I am not sure about the "Fixed" releases. In case we create a new version of the 'old' patch, the new patch release will be added above of the "Fixed" release, and it may confuse our customers.

@RomanChernyk @olegburov Since the amount of effort to add a reference to the plaintext is the same as for creating a badge. 
* Badge +1

**Comment by olegburov** [comment]
The [README.MD](https://github.com/SitecoreSupport/Readme#bug-was-fixed-in-next-product-update) is updated now.
