### ISSUE TITLE
Release bot spams notifications

### ISSUE THREAD

**Issue by RomanChernyk** [SitecoreSupport/ReleaseDaemon#78]
Once a person publishes any patch, he/she receives a notification for each and every patch released later:
https://github.com/SitecoreSupport/Notifications/issues/1

This happens because once the person is mentioned in the thread, he/she is automatically subscribed to further updates.

**Comment by AlenPelin** [comment]
I propose to create new issues per username and append comments there. So each user can subscribe/unsubscribe from any user. So reviewer can subscribe to its padavans. 

With this approach code change is minimal - just an extra step required to find an issue number or create it if it's missing.
